/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteRouteImport } from './routes/account/route'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AccountAddressRouteImport } from './routes/account/address'
import { Route as AccountPaymentRouteImport } from './routes/account/payment'
import { Route as AccountProfileRouteImport } from './routes/account/profile'
import { Route as CategoryIdRouteImport } from './routes/category.$id'
import { Route as OwnerIndexRouteImport } from './routes/owner/index'
import { Route as OwnerAdminRouteImport } from './routes/owner/admin'
import { Route as ProductIdRouteImport } from './routes/product.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRouteRoute = AccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountAddressRoute = AccountAddressRouteImport.update({
  id: '/address',
  path: '/address',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountPaymentRoute = AccountPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRouteRoute,
} as any)
const CategoryIdRoute = CategoryIdRouteImport.update({
  id: '/category/$id',
  path: '/category/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/owner/',
  path: '/owner/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerAdminRoute = OwnerAdminRouteImport.update({
  id: '/owner/admin',
  path: '/owner/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/cart': typeof CartRoute
  '/account/address': typeof AccountAddressRoute
  '/account/payment': typeof AccountPaymentRoute
  '/account/profile': typeof AccountProfileRoute
  '/category/$id': typeof CategoryIdRoute
  '/owner/admin': typeof OwnerAdminRoute
  '/product/$id': typeof ProductIdRoute
  '/account/': typeof AccountIndexRoute
  '/owner/': typeof OwnerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/account/address': typeof AccountAddressRoute
  '/account/payment': typeof AccountPaymentRoute
  '/account/profile': typeof AccountProfileRoute
  '/category/$id': typeof CategoryIdRoute
  '/owner/admin': typeof OwnerAdminRoute
  '/product/$id': typeof ProductIdRoute
  '/account': typeof AccountIndexRoute
  '/owner': typeof OwnerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/cart': typeof CartRoute
  '/account/address': typeof AccountAddressRoute
  '/account/payment': typeof AccountPaymentRoute
  '/account/profile': typeof AccountProfileRoute
  '/category/$id': typeof CategoryIdRoute
  '/owner/admin': typeof OwnerAdminRoute
  '/product/$id': typeof ProductIdRoute
  '/account/': typeof AccountIndexRoute
  '/owner/': typeof OwnerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/cart'
    | '/account/address'
    | '/account/payment'
    | '/account/profile'
    | '/category/$id'
    | '/owner/admin'
    | '/product/$id'
    | '/account/'
    | '/owner/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/account/address'
    | '/account/payment'
    | '/account/profile'
    | '/category/$id'
    | '/owner/admin'
    | '/product/$id'
    | '/account'
    | '/owner'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/cart'
    | '/account/address'
    | '/account/payment'
    | '/account/profile'
    | '/category/$id'
    | '/owner/admin'
    | '/product/$id'
    | '/account/'
    | '/owner/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRouteRoute: typeof AccountRouteRouteWithChildren
  CartRoute: typeof CartRoute
  CategoryIdRoute: typeof CategoryIdRoute
  OwnerAdminRoute: typeof OwnerAdminRoute
  ProductIdRoute: typeof ProductIdRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/address': {
      id: '/account/address'
      path: '/address'
      fullPath: '/account/address'
      preLoaderRoute: typeof AccountAddressRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/payment': {
      id: '/account/payment'
      path: '/payment'
      fullPath: '/account/payment'
      preLoaderRoute: typeof AccountPaymentRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/category/$id': {
      id: '/category/$id'
      path: '/category/$id'
      fullPath: '/category/$id'
      preLoaderRoute: typeof CategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/': {
      id: '/owner/'
      path: '/owner'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/admin': {
      id: '/owner/admin'
      path: '/owner/admin'
      fullPath: '/owner/admin'
      preLoaderRoute: typeof OwnerAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountRouteRouteChildren {
  AccountAddressRoute: typeof AccountAddressRoute
  AccountPaymentRoute: typeof AccountPaymentRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
  AccountAddressRoute: AccountAddressRoute,
  AccountPaymentRoute: AccountPaymentRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
  AccountRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRouteRoute: AccountRouteRouteWithChildren,
  CartRoute: CartRoute,
  CategoryIdRoute: CategoryIdRoute,
  OwnerAdminRoute: OwnerAdminRoute,
  ProductIdRoute: ProductIdRoute,
  OwnerIndexRoute: OwnerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
